title: Dong-gi Lee # your name (or website title) here
logo: "/Photo_DGLee.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <b>Research Assistant Professor</b> <br>
  Department of Psychiatry, <br>
  Ajou University School of Medicine <br>
  <br>
  E-mail: ldg1226@ajou.ac.kr<br>  
  <br>
  <a href="https://scholar.google.com/citations?view_op=list_works&hl=ko&user=kvj78DIAAAAJ">View My Google Scholar Profile</a>   
theme: jekyll-theme-minimal
